name:  HeatMap
author:  davidwalsh
current:  0.1
category:  Interface
tags:  [heatmap,events,click,ajax]
docs:  http://davidwalsh.name/js/heatmap
demo:  http://davidwalsh.name/dw-content/heat-map.php
